version: "3"
# https://hub.docker.com/_/postgres
services:
  postgres:
    image: postgres:9.6-alpine
    restart: no
    environment:
      POSTGRES_USER: bro
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
    volumes:
      - "my-custom-amazing-volume:/var/lib/postgresql/data"
